# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_add_cpp <- function(x, y) {
    .Call(`_xtensor_test_add_cpp`, x, y)
}

test_in_place_modify_cpp <- function(x) {
    .Call(`_xtensor_test_in_place_modify_cpp`, x)
}

test_reshape_cpp <- function(x) {
    .Call(`_xtensor_test_reshape_cpp`, x)
}

test_int_cpp <- function(x) {
    .Call(`_xtensor_test_int_cpp`, x)
}

test_lgl_cpp <- function(x) {
    .Call(`_xtensor_test_lgl_cpp`, x)
}

test_stdcomplex_cpp <- function(x) {
    .Call(`_xtensor_test_stdcomplex_cpp`, x)
}

xtensor_r_example <- function(tens) {
    .Call(`_xtensor_xtensor_r_example`, tens)
}

