jobs:
  - job: 'Linux_1'
    strategy:
      matrix:
        gcc_6:
          gcc_version: '6'
        gcc_6_novendor:
          gcc_version: '6'
          novendor: '1'
        gcc_7:
          gcc_version: '7'
        gcc_7_novendor:
          gcc_version: '7'
          novendor: '1'
        gcc_7_novendor_dev:
          gcc_version: '7'
          novendor: '1'
          dev_xtensor: '1'
        gcc_8:
          gcc_version: '8'
        gcc_8_novendor:
          gcc_version: '8'
          novendor: '1'
        gcc_8_novendor_dev:
          gcc_version: '8'
          novendor: '1'
          dev_xtensor: '1'
        gcc_9:
          gcc_version: '9'
        gcc_9_novendor:
          gcc_version: '9'
          novendor: '1'
        gcc_9_novendor_dev:
          gcc_version: '9'
          novendor: '1'
          dev_xtensor: '1'
    pool:
      vmImage: ubuntu-18.04
    variables:
      CC: gcc-$(gcc_version)
      CXX: g++-$(gcc_version)
      NOVENDOR: ${novendor}
      USE_DEV_XTENSOR_R: ${dev_xtensor}
    timeoutInMinutes: 360
    steps:

      - script: |
          if [[ $(gcc_version) == '6' || $(gcc_version) == '7' || $(gcc_version) == '8' ]]; then
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get --no-install-suggests --no-install-recommends install g++-$(gcc_version)
          fi
        displayName: Install build toolchain

      - script: |
          sudo apt-get install -y texlive-latex-base texlive-latex-recommended texinfo texlive-fonts-extra texlive-fonts-recommended
        displayName: Install latex for R checks
 
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      - template: unix-build.yml
