steps:
  - script: |
      conda config --set always_yes yes --set changeps1 no
      conda update -q conda
      conda env create --file environment-dev.yml
    displayName: Install dependencies

  - script: |
      # If NOVENDOR is set, install xtensor-r and dependencies in conda environment.
      # If USE_DEV_XTENSOR_R is set, xtensor-r will be installed from source instead
      # of using the conda package
      if [[ $NOVENDOR == 1 ]]; then
          if [[ $USE_DEV_XTENSOR_R == 1 ]]; then
              source activate xtensor-dev
              conda install xtensor==0.24.0 xsimd=8.0.3 cmake -c conda-forge;
              git clone https://github.com/xtensor-stack/xtensor-r.git;
              cd xtensor-r; mkdir build; cd build;
              cmake -D CMAKE_INSTALL_PREFIX=$CONDA_PREFIX ..;
              make install;
              cd ../..;
          else
              conda install -n xtensor-dev xtensor-r==0.13.0 -c conda-forge;
          fi
      fi
    displayName: Install NOVENDOR dependencies
    workingDirectory: $(Build.BinariesDirectory)

  - script: |
      source activate xtensor-dev
      R CMD build $(Build.SourcesDirectory);
    displayName: Build Xtensor.R
    workingDirectory: $(Build.BinariesDirectory)

  - script: |
      source activate xtensor-dev
      if [[ $(uname -s) == Darwin* ]]; then
          export NO_MANUAL=--no-manual;
      fi
      if [[ $NOVENDOR == 1 ]]; then
          echo "Running R CMD check with --novendor argument";
          echo "R CMD check --install-args=\"--configure-args='--novendor'\" $NO_MANUAL ./xtensor_*.tar.gz"
          R CMD check --install-args="--configure-args='--novendor'" $NO_MANUAL ./xtensor_*.tar.gz || (
           cat xtensor-stack/Xtensor.R/xtensor.Rcheck/00install.out &&
           cat xtensor-stack/Xtensor.R/xtensor.Rcheck/00check.log   &&
           cat xtensor-stack/Xtensor.R/xtensor.Rcheck/Rdlatex.log
          );
      else
          echo "Running R CMD check with --as-cran argument.";
          echo "R CMD check --as-cran $NO_MANUAL ./xtensor_*.tar.gz"
          R CMD check --as-cran $NO_MANUAL ./xtensor_*.tar.gz || (
           cat xtensor-stack/Xtensor.R/xtensor.Rcheck/00install.out &&
           cat xtensor-stack/Xtensor.R/xtensor.Rcheck/00check.log   &&
           cat xtensor-stack/Xtensor.R/xtensor.Rcheck/Rdlatex.log
          );
      fi
    displayName: Check R package
    workingDirectory: $(Build.BinariesDirectory)
